# Schema for configuration files of the Backup and Migrate module.

backup_migrate.profile.*:
  type: config_entity
  label: 'Backup and Migrate profile'
  mapping:
    name:
      type: string
    label:
      type: label
      label: 'Label'
    filename:
      type: string
      label: 'Filename'
    append_timestamp:
      type: boolean
      label: 'Append Timestamp'
    timestamp_format:
      type: string
      label: 'Timestamp Format'

backup_migrate.backup_migrate_schedule.*:
  type: config_entity
  label: 'Backup and Migrate Schedule'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Schedule Name'
    uuid:
      type: string
    enabled:
      type: boolean
      label: 'Enabled'
    keep:
      type: integer
      label: 'Backups to keep'
    period:
      type: integer
      label: 'Frequency'
    cron:
      type: boolean
      label: 'Run on cron'
    source_id:
      type: string
      label: 'Source'
    destination_id:
      type: string
      label: 'Destination'
    settings_profile_id:
      type: string
      label: 'Settings Profile'

backup_migrate.backup_migrate_settings.*:
  type: config_entity
  label: 'Backup and Migrate Settings'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    config:
      type: mapping
      label: 'Configuration'
      mapping:
        namer:
          type: mapping
          mapping:
            filename:
              type: string
            timestamp:
              type: integer
            timestamp_format:
              type: string
        compressor:
          type: mapping
          mapping:
            compression:
              type: string
        encrypt:
          type: mapping
          mapping:
            encrypt:
              type: integer
            encrypt_password:
              type: string
        utils:
          type: mapping
          mapping:
            site_offline:
              type: integer
        metadata:
          type: mapping
          mapping:
            description:
              type: string
        db_exclude:
          type: mapping
          mapping:
            exclude_tables:
              type: sequence
              sequence:
                type: string
            nodata_tables:
              type: sequence
              sequence:
                type: string
        private_files_exclude:
          type: mapping
          mapping:
            exclude_filepaths:
              type: sequence
              sequence:
                type: string
        public_files_exclude:
          type: mapping
          mapping:
            exclude_filepaths:
              type: sequence
              sequence:
                type: string

backup_migrate.backup_migrate_destination.*:
  type: config_entity
  label: 'Backup Destination'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    type:
      type: string
      label: 'Destination Type'
    config:
      type: sequence
      label: 'Configuration'
      sequence:
        type: string

backup_migrate.backup_migrate_source.*:
  type: config_entity
  label: 'Backup Source'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    type:
      type: string
      label: 'Source Type'
    config:
      type: sequence
      label: 'Configuration'
      sequence:
        type: string
