<?php

/**
 * @file
 * Functions to support theming in the Bartik theme.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Template\Attribute;

/**
 * Implements hook_preprocess_HOOK() for HTML document templates.
 *
 * Adds body classes if certain regions have content.
 */
function assessment_preprocess_node(&$variables)
{
 $result = array();
 $result =  explode("=",$_SERVER['QUERY_STRING']);
 
 $variables['url_string'] = $result[1];


}